blog/urls.py
from django.urls import path

from . import views
from.import apps
app_name = apps.BlogConfig.name
urlpatterns = [
    path("", views.StartingPageView.as_view(), name="starting-page"),
    path("posts", views.AllPostsView.as_view(), name="posts-page"),
    path("posts/<slug:slug>", views.SinglePostView.as_view(),
         name="post-detail-page"),  # /posts/my-first-post
    path("read-later", views.ReadLaterView.as_view(), name="read-later")
]

gitproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/",include("blog.urls",namespace ="blog")),
    path('login/',auth_view.LoginView.as_view(template_name='blog/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('user/',include("users.urls")),
]+ static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)    

blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.


class Tag(models.Model):
    caption = models.CharField(max_length=20)

    def __str__(self):
        return self.caption


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email_address = models.EmailField()

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name()


class Post(models.Model):
    title = models.CharField(max_length=150)
    excerpt = models.CharField(max_length=200)
    image = models.ImageField(upload_to="posts", null=True)
    date = models.DateField(auto_now=True)
    slug = models.SlugField(unique=True, db_index=True)
    content = models.TextField(validators=[MinLengthValidator(10)])
    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="posts")
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user_name = models.CharField(max_length=120)
    user_email = models.EmailField() 
    text = models.TextField(max_length=400)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from django.views import View

from .models import Post
from blog.form import CommentForm

# Create your views here.


class StartingPageView(ListView):
    template_name = "blog/index.html"
    model = Post
    ordering = ["-date"]
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        data = queryset[:3]
        return data


class AllPostsView(ListView):
    template_name = "blog/all_post.html"
    model = Post
    ordering = ["-date"]
    context_object_name = "all_posts"


class SinglePostView(View):
    def is_stored_post(self, request, post_id):
        stored_posts = request.session.get("stored_posts")
        if stored_posts is not None:
          is_saved_for_later = post_id in stored_posts
        else:
          is_saved_for_later = False

        return is_saved_for_later

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        
        context = {
            "post": post,
            "post_tags": post.tags.all(),
            "comment_form": CommentForm(),
            "comments": post.comments.all().order_by("-id"),
            "saved_for_later": self.is_stored_post(request, post.id)
        }
        return render(request, "blog/post-detail.html", context)

    def post(self, request, slug):
        comment_form = CommentForm(request.POST)
        post = Post.objects.get(slug=slug)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()

            return HttpResponseRedirect(reverse("post-detail-page", args=[slug]))

        context = {
            "post": post,
            "post_tags": post.tags.all(),
            "comment_form": comment_form,
            "comments": post.comments.all().order_by("-id"),
            "saved_for_later": self.is_stored_post(request, post.id)
        }
        return render(request, "blog/post-detail.html", context)


class ReadLaterView(View):
    def get(self, request):
        stored_posts = request.session.get("stored_posts")

        context = {}

        if stored_posts is None or len(stored_posts) == 0:
            context["posts"] = []
            context["has_posts"] = False
        else:
          posts = Post.objects.filter(id__in=stored_posts)
          context["posts"] = posts
          context["has_posts"] = True

        return render(request, "blog/readlater.html", context)


    def post(self, request):
        stored_posts = request.session.get("stored_posts")

        if stored_posts is None:
          stored_posts = []

        post_id = int(request.POST["post_id"])

        if post_id not in stored_posts:
          stored_posts.append(post_id)
        else:
          stored_posts.remove(post_id)

        request.session["stored_posts"] = stored_posts
        
        return HttpResponseRedirect("/")

blog/templates/blog/all_post.html
{% extends "base.html" %}
{% load static %}

{% block title %} 
All My Posts
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "blog/post.css" %}" />
  <link rel="stylesheet" href="{% static "blog/all-posts.css" %}" />
{% endblock %}

{% block content %}
<section id="all-posts">
  <h2>My Collected Posts</h2>

  <ul>
    {% for post in all_posts %}
      {% include "blog/includes/post.html" %}
    {% endfor %}
  </ul>
</section>
{% endblock %}

blog/templates/blog/create.html
{% block title %} register {% endblock %}


{% if messages %}
 {%for message in messages %}
 <div class="alert alert-{{message.tag}}">{{message}}</div>
 {% endfor %}
{%endif%}
{% block content %}
{% if form.errors %}
{% for field in form %}

     {% for error in field.errors %}
          {{field.label}}: {{ error|escape }}
     {% endfor %}

{% endfor %}
{% endif %}

    <form method="post" ,enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.as_p}}
        {{from.error}}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
My Blog 
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "blog/post.css" %}" />
  <link rel="stylesheet" href="{% static "blog/index.css" %}" />
{% endblock %}

{% block content %}
<section id="welcome">
  <header>
    <img src="{% static "blog/images/mj.jpg" %}" alt="Mj - The Author Of This Blog" />
    <h2>MAXIMILIAN'S BLOG</h2>
  </header>
  <p>Hi, I am Max and I love to blog about tech and the world!</p>
</section>

<section id="latest-posts">
  <h2>My Latest Thoughts</h2>

  <ul>
    {% for post in posts %}
      {% include "blog/includes/post.html" %}
    {% endfor %}
  </ul>
</section>

<section id="about">
  <h2>What I Do</h2>
  <p>
    I love programming, I love to help others and I enjoy exploring new
    technologies in general!
  </p>
  <p>
    My goal is to keep on growing as a developer - and if I could help you do
    the same, I'd be very happy!
  </p>
</section>
{% endblock %}

blog/templates/blog/login.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>login</title>
 </head>
 <body>
    {% if messages %}
    {%for message in messages %}
    <div class="alert alert-{{message.tag}}">{{message}}</div>
    {% endfor %}
   {%endif%}

   <form method="post" >
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
     
 </body>
 </html>

blog/templates/blog/logout.html
<!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>login</title>
 </head>
 <body>
    {% if messages %}
    {%for message in messages %}
    <div class="alert alert-{{message.tag}}">{{message}}</div>
    {% endfor %}
   {%endif%}
   <a href="{% url 'starting-page' %}">Home</a>
</form>
     
 </body>
 </html>

blog/templates/blog/post-detail.html
{% extends "base.html" %} 
{% load static %} 

{% block title %} 
{{ post.title }}
{% endblock %} 

{% block css_files %} 
<link rel="stylesheet" href="{% static "blog/post-detail.css" %}" /> 
{% endblock %} 

{% block content %}

{% if comment_form.errors %}
  <div id="alert">
    <h2>Saving the comment failed!</h2>
    <p>Please check the comment form below the post and fix your erros.</p>
    <a href="#comment-form">Fix!</a>
  </div>
{% endif %}

<section id="summary">
  <h2>{{ post.title }}</h2>
  <div>
    {% for tag in post_tags %}
      <span class="tag">{{ tag.caption }}</span>
    {% endfor %}
  </div>
  <div id="read-later">
    <form action="{% url "blog:read-later" %}" method="POST">
      {% csrf_token %}
      <input type="hidden" value="{{ post.id }}" name="post_id">
      <button>
        {% if saved_for_later %}
          Remove from "Read Later" List
        {% else %}
          Read Later
        {% endif %}
      </button>
    </form>
  </div>
  <article>
    <img src="{{ post.image.url }}" alt="{{ post.title }}" />
    <address>By <a href="mailto:{{ post.author.email_address }}">{{ post.author }}</a></address>
    <div>Last updated on <time>{{ post.date|date:"d M Y" }}</time></div>
  </article>
</section>

<main>
  {{ post.content|linebreaks }}
</main>

<section id="comments">
  <ul>
    {% for comment in comments %}
      <li>
        <h2>{{ comment.user_name }}</h2>
        <p>{{ comment.text|linebreaks }}</p>
      </li>
    {% endfor %}
  </ul>
</section>

<section id="comment-form">
  <h2>Your Comment</h2>
  <form action="{% url "blog:post-detail-page" post.slug %}" method="POST">
    {% csrf_token %}
    {% for form_field in comment_form %}
      <div class="form-control {% if form_field.errors %}invalid{% endif %}">
        {{ form_field.label_tag }}
        {{ form_field }}
        {{ form_field.errors }}
      </div>
    {% endfor %}
    <button>Save Comment</button>
  </form>
</section>
{% endblock %}

blog/templates/blog/readlater.html
{% extends "base.html" %}
{% load static %}

{% block title %} 
My Stored Posts
{% endblock %} 

{% block css_files %}
<link rel="stylesheet" href="{% static "blog/stored-posts.css" %}">
{% endblock %}

{% block content %}
  <section id="stored-posts">
    {% if not has_posts %}
      <p>You didn't save any posts for later.</p>
    {% endif %}
    <ul>
      {% for post in posts %}
        <li><a href="{% url "blog:post-detail-page" post.slug %}">{{ post.title }}</a></li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}

blog/templates/blog/register.html
 
{% block title %} register {% endblock %}


{% if messages %}
 {%for message in messages %}
 <div class="alert alert-{{message.tag}}">{{message}}</div>
 {% endfor %}
{%endif%}
{% block content %}

    <form method="post" >
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}