blog/urls.py
from django.urls import path

from . import views
from.import apps
app_name = apps.BlogConfig.name
urlpatterns = [
    path("", views.StartingPageView.as_view(), name="starting-page"),
    path("posts", views.AllPostsView.as_view(), name="posts-page"),
    path("posts/<slug:slug>", views.SinglePostView.as_view(),
         name="post-detail-page"),  # /posts/my-first-post
    path("read-later", views.ReadLaterView.as_view(), name="read-later")
]

gitproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/",include("blog.urls",namespace ="blog")),
    path('login/',auth_view.LoginView.as_view(template_name='blog/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('user/',include("users.urls")),
]+ static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static "app.css" %}">
  {% block css_files %}{% endblock %}
</head>
<body>
  <header id="main-navigation">
    <h1><a href="{% url 'blog:starting-page' %}">Mj' Blog</a></h1>
    <nav>
      <a href="{% url 'blog:read-later' %}">Stored Posts</a>
      <a href="{% url 'blog:posts-page' %}">All Posts</a>
    </nav>
  </header>

  {% block content %}
  {% endblock %}
</body>
</html>